#!/usr/bin/env node
/**
 * facets.json manifest generator/checker (brief §4.1, §8.2).
 *
 * Modes:
 *   node scripts/manifest.mjs write   — regenerate contracts/facets.json from forge artifacts
 *   node scripts/manifest.mjs check   — fail if facets.json is stale, or on selector
 *                                       collisions between facets that could both be cut in
 *
 * The manifest is the off-chain mirror of the loupe: name → selectors (→ address, filled
 * per network after deployment). CI runs `check` on every PR; the diamond test suite
 * asserts the on-chain loupe matches this file after every cut.
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const contractsDir = join(root, "contracts");
const manifestPath = join(contractsDir, "facets.json");

/** Facets that make up the deployed diamond. AeroFacet is deliberately absent from the
 *  default set until finalized against published v3 code (M5); MockAeroFacet is test-only.
 *  `group` marks mutually exclusive protocol facets — they intentionally share the
 *  IProtocolFacet selector set and swap via diamondCut. */
const FACETS = [
  { name: "DiamondCutFacet", deployed: true },
  { name: "DiamondLoupeFacet", deployed: true },
  { name: "OwnershipFacet", deployed: true },
  { name: "AccessFacet", deployed: true },
  { name: "CustodyFacet", deployed: true },
  { name: "TrancheFacet", deployed: true },
  { name: "TargetsFacet", deployed: true },
  { name: "ExecutionFacet", deployed: true },
  { name: "AerodromeFacet", deployed: true, group: "protocol" },
  { name: "MockAeroFacet", deployed: false, group: "protocol" },
  { name: "AeroFacet", deployed: false, group: "protocol" },
];

function selectorsOf(name) {
  const raw = execSync(`forge inspect ${name} methodIdentifiers --json`, {
    cwd: contractsDir,
    encoding: "utf8",
  });
  const map = JSON.parse(raw);
  // sig -> selector; normalize to sorted [{ sig, selector }]
  return Object.entries(map)
    .map(([sig, sel]) => ({ sig, selector: `0x${sel}` }))
    .sort((a, b) => (a.selector < b.selector ? -1 : 1));
}

function build() {
  const facets = FACETS.map((f) => {
    const selectors = selectorsOf(f.name);
    return {
      name: f.name,
      deployed: f.deployed,
      ...(f.group ? { group: f.group } : {}),
      selectors,
      // flat list for Foundry scripts/tests (vm.parseJsonStringArray)
      selectorList: selectors.map((s) => s.selector),
    };
  });
  return { schemaVersion: 1, note: "generated by scripts/manifest.mjs — do not edit selectors by hand", facets };
}

function checkCollisions(manifest) {
  const errors = [];
  // Collisions are fatal between any two facets that could be live simultaneously —
  // i.e. any pair not sharing a `group`.
  const seen = new Map(); // selector -> { facet, group, sig }
  for (const f of manifest.facets) {
    for (const { sig, selector } of f.selectors) {
      const prev = seen.get(selector);
      if (prev && !(prev.group && prev.group === f.group)) {
        errors.push(`selector collision ${selector} (${sig}): ${prev.facet} vs ${f.name}`);
      }
      if (!prev) seen.set(selector, { facet: f.name, group: f.group, sig });
    }
  }
  // Protocol facets must expose an identical IProtocolFacet surface: compare their shared
  // selector sets pairwise on the interface functions (those present in all of them).
  const protocol = manifest.facets.filter((f) => f.group === "protocol");
  if (protocol.length > 1) {
    const sets = protocol.map((f) => new Set(f.selectors.map((s) => s.selector)));
    const base = protocol[0];
    const IPROTOCOL_SIGS = [
      "protocolId()",
      "createStake(uint256,uint256,bool)",
      "allocate(uint256,address[],uint256[])",
      "resetAllocation(uint256)",
      "claim(uint256,bytes)",
      "compound(uint256,uint256,bytes)",
      "positionWeight(uint256)",
      "cooldownRemaining(uint256)",
      "protocolCooldown()",
      "allocationWindow()",
    ];
    for (const sig of IPROTOCOL_SIGS) {
      const sel = base.selectors.find((s) => s.sig === sig)?.selector;
      if (!sel) {
        errors.push(`protocol facet ${base.name} missing IProtocolFacet function ${sig}`);
        continue;
      }
      sets.forEach((set, i) => {
        if (!set.has(sel)) errors.push(`protocol facet ${protocol[i].name} missing IProtocolFacet function ${sig}`);
      });
    }
  }
  return errors;
}

const mode = process.argv[2] ?? "check";
const fresh = build();
const collisions = checkCollisions(fresh);
if (collisions.length) {
  console.error("manifest FAILED:\n" + collisions.join("\n"));
  process.exit(1);
}

if (mode === "write") {
  writeFileSync(manifestPath, JSON.stringify(fresh, null, 2) + "\n");
  console.log(`wrote ${manifestPath} (${fresh.facets.length} facets)`);
} else {
  if (!existsSync(manifestPath)) {
    console.error("manifest FAILED: contracts/facets.json missing — run `node scripts/manifest.mjs write`");
    process.exit(1);
  }
  const committed = JSON.parse(readFileSync(manifestPath, "utf8"));
  const strip = (m) => JSON.stringify({ ...m, facets: m.facets.map(({ address, ...f }) => f) });
  if (strip(committed) !== strip(fresh)) {
    console.error("manifest FAILED: contracts/facets.json is stale — run `node scripts/manifest.mjs write` and review the diff");
    process.exit(1);
  }
  console.log("manifest OK: facets.json matches artifacts, no selector collisions");
}
